Potential_?.png: plotter.py output.txt
	python plotter.py
#	#rm -f output.txt placas

placas: placas_C.c
	mpicc -o placas placas_C.c -lm

output.txt: camilor_placas.o?????
	mv camilor_placas.o????? output.txt


